# -*- coding: utf-8 -*-
"""Projeto Machine Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16wekjatEpITeoz6ZG1rm_Y1kFIlExAPy
"""

import pandas as pd
import seaborn as sns

df = pd.read_csv('https://cliente.imagepat.com.br/smoking_driking_dataset_Ver01.csv')

df

df.shape

# Devido ao tamanho do dataset, iremos trabalhar com uma amostra representativa dele (20%)
# Ao fazer as análises necessárias e fazer com que um modelo trabalhe bem em cima desse sample,
# faremos com que ele rode em cima de todos os dados e avaliaremos sua performance.

df_20 = df.sample(frac=0.2)
df_20

"""Iniciaremos com uma anáise dos dados para depois prosseguirmos com uma preparação dos dados e treinamento de um modelo"""

df.dtypes

"""Os dados de todas as colunas são do tipo numérico, com exceção da coluna `sexo` e da coluna `Bebe_SN`."""

sns.pairplot(df)

